### ISSUE TITLE
Embed Qt translation resources

### ISSUE THREAD

**Issue by projekter** [dannyedel/dspdfviewer#119]
The new system of embedding translations works well, but Qt's translation files are not included in the application.

**Comment by dannyedel** [comment]
You're right. These are, for example, the labels in the File-Chooser form.

I'll see that I add a method to include them too, probably hidden behind a cmake switch.

On my platform (dynamically linked with dependency package manager) the translations are shipped with the qt libs, so they were always present at runtime, thus I didn't notice.
