### ISSUE TITLE
Does it support Chinese?

### ISSUE THREAD

**Issue by zhangkmsjtu** [dannyedel/dspdfviewer#163]
Does it support Chinese?

**Comment by dannyedel** [comment]
Yes and no:

* Yes, it should™ support LaTeX documents containing chinese characters, as long as the fonts are embedded in the PDF file.  If this doesn't work, please create a demonstation pdf and I'll investigate.
* No, the *user interface* is not yet translated.
  * If you want to add a translation, you will need to add your new translation file in two places:
    [cmake/filelists.cmake][1] and [dspdfviewer.qrc][2]
  * Then configure with `cmake -DUpdateTranslations=ON` and it should™ generate the translation file.

[1]: https://github.com/dannyedel/dspdfviewer/blob/8aadd17b35c9adaa88e87d2b23d68eac64c5a768/cmake/filelists.cmake#L6
[2]: https://github.com/dannyedel/dspdfviewer/blob/8aadd17b35c9adaa88e87d2b23d68eac64c5a768/dspdfviewer.qrc

**Comment by zhangkmsjtu** [comment]
\documentclass{beamer}
\usepackage{pgfpages}
\setbeameroption{show notes on second screen}
%\usepackage[timeinterval=1]{tdclock}%dspdfviewer不支持tdclock宏包
\usepackage[UTF8,scheme=plain]{ctex}

\usetheme{Madrid}

\title{中文标题Chinese Title}
\author{中文名Chinese name}
\date{\today}
\institute{sjtu单位}

\begin{document}

\maketitle

\section{Introduction}

\begin{frame}
 \frametitle{Introduction}
\begin{itemize}
\item 测试
\note{笔记}
\item 这里显示中文
\item 这里也显示中文
\end{itemize}
\end{frame}

\end{document}

**Comment by zhangkmsjtu** [comment]
[Beamer_Chinese.zip](https://github.com/dannyedel/dspdfviewer/files/201147/Beamer_Chinese.zip)

**Comment by zhangkmsjtu** [comment]
The Chinese fonts cannot be displayed on a dspdfviewer.

**Comment by dannyedel** [comment]
Thanks for the document upload.  I'll look into the issue and report back.

**Comment by dannyedel** [comment]
Hi @zhangkmsjtu I tried to view the PDF you supplied in the zip with dspdfviewer (current master from source, and additionally checked the Debian stretch and Debian sid binaries), and it displayed the following on the helper monitor:

![screenshot](https://cloud.githubusercontent.com/assets/782418/14231641/4b4b634e-f98b-11e5-8ed0-6ca5fe66ed8b.png)

To me, this looks like it worked.  To figure out why it doesn't for you, please provide the following information:

* What platform (Operating System and Desktop Environment) are you using
* What version of dspdfviewer are you running (output of `dspdfviewer --version` or check the `F1` help box when its running)
* Did you install from a binary (if yes, where from) or compile yourself from source (if yes, against which Qt and Poppler version)

Also, a quick search on the web suggests that sometimes, the package package `poppler-data` was not installed which is needed to render Chinese documents.

According to `pdffonts`, the file you uploaded has the fonts embedded so this is not an issue here.

**Comment by zhangkmsjtu** [comment]
Specific infromation:
windows 7, v1.14
![dspdf4](https://cloud.githubusercontent.com/assets/12411065/14231881/8df6105a-f9c6-11e5-99bc-4fda79351310.jpg)
![dspdf3](https://cloud.githubusercontent.com/assets/12411065/14231883/af8cd834-f9c6-11e5-9692-2ce7f2fe3e05.png)
![dspdf2](https://cloud.githubusercontent.com/assets/12411065/14231889/e0600698-f9c6-11e5-8270-17a62ae144ec.jpg)
![dspdf](https://cloud.githubusercontent.com/assets/12411065/14231890/e0607f6a-f9c6-11e5-8bff-29c75331da4a.png)

**Comment by dannyedel** [comment]
Thank you for the detailed information! This should™ be all the info needed to reproduce and debug this.

> windows 7, v1.14

I will CC @projekter on this, since he's the windows expert.  In the meantime, I will try to reproduce this in a windows 7 VM and see if I can improve on the situation.

**Comment by zhangkmsjtu** [comment]
Thank you very much for everything you do.

**Comment by dannyedel** [comment]
Progress report:  This is *definitely* the missing `poppler-data` package.

I can reproduce the problem on a Linux host by removing the poppler-data package, I get the exact same result (chinese glyphs don't get rendered at all).

I will try to figure out where to copy the files on a windows machine.

**Comment by projekter** [comment]
Yes, I had to build poppler without the data package. But the reason for this was that I could not figure out where to put this package and how to configure poppler so that it actually uses it. So any hints will be appreciated, I'm sure this can be fixed easily.

**Comment by dannyedel** [comment]
@projekter: On a Linux host the poppler-data gets installed into `/usr/share/poppler/` and `/var/lib/ghostscript`, see [debian listing][1] for example.

When running on Debian with `strace -e open -f dspdfviewer`, I don't see any attempt to load files from the "ghostscript" directory, so I'm not sure if that part is really needed.

I think it should™ be possible to tell poppler at the cmake time which directory name to embed in the library as a search path to poppler-data; Setting the variable `POPPLER_DATADIR` at [poppler cmake][2] time might™ work.

----

If you have a tool that can print out which files a windows program tries to load, its output might help a lot in figuring out where to place the files (without recompiling).  Example strace output without poppler-data installed:

```text
Failed to load qt translations for locale "C"
Failed to load dspdfviewer translation for current locale "C"
[pid 23588] open("/home/danny/.config/dspdfviewer.ini", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 23588] open("/home/danny/tmp/dsp-ticket163/Beamer_Chinese.pdf", O_RDONLY|O_CLOEXEC) = 7
[pid 23588] open("/usr/share/poppler/nameToUnicode", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 23588] open("/usr/share/poppler/cidToUnicode", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 23588] open("/usr/share/poppler/unicodeMap", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 23588] open("/usr/share/poppler/cMap", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```

After installing poppler-data to /usr/share/poppler (with correct output):

```text
Failed to load qt translations for locale "C"
Failed to load dspdfviewer translation for current locale "C"
[pid 23635] open("/home/danny/.config/dspdfviewer.ini", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 23635] open("/home/danny/tmp/dsp-ticket163/Beamer_Chinese.pdf", O_RDONLY|O_CLOEXEC) = 7
[pid 23635] open("/usr/share/poppler/nameToUnicode", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 8
[pid 23635] open("/usr/share/poppler/nameToUnicode/Thai", O_RDONLY) = 9
[pid 23635] open("/usr/share/poppler/nameToUnicode/Greek", O_RDONLY) = 9
[pid 23635] open("/usr/share/poppler/nameToUnicode/Bulgarian", O_RDONLY) = 9
[pid 23635] open("/usr/share/poppler/cidToUnicode", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 8
[pid 23635] open("/usr/share/poppler/unicodeMap", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 8
[pid 23635] open("/usr/share/poppler/cMap", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 8

(...)

[pid 23638] open("/usr/share/poppler/cidToUnicode/Adobe-GB1", O_RDONLY) = 10
[pid 23638] open("/usr/share/poppler/cMap/Adobe-GB1/Identity-H", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 23638] open("/usr/share/poppler/ColorProfiles/display.icc", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 23638] open("/usr/share/poppler/ColorProfiles/RGB.icc", O_RDONLY) = -1 ENOENT (No such file or directory)
```

So in this case, it seems to be the `Adobe-GB1` file that it needs to load.

[1]: https://packages.debian.org/sid/all/poppler-data/filelist
[2]: https://cgit.freedesktop.org/poppler/poppler/tree/CMakeLists.txt#n286

**Comment by projekter** [comment]
So poppler-data is kind of a standalone, that does not need to be compiled into poppler? That's interesting.
The problem I had is that in all instructions you are told to extract poppler-data to `/usr/share/poppler`. As this is not a valid path on Windows, I tried to figure out where to change it, but I could not figure out a cmd switch, and I remember I found a statement that this path is hardcoded into poppler. As everything worked without poppler-data, I did not investigate further, but now I'll do so.

**Comment by dannyedel** [comment]
@projekter:  The path `/usr/share` apparently gets mapped to `C:/dspdf/` by default. I got this by running https://live.sysinternals.com/Procmon.exe against "Program Name is dspdfviewer.exe, Operation is CreateFile" -- which is a bit misleading, but apparently CreateFile also captures "open existing file" attempts.

----

@zhangkmsjtu As a temporary workaround, you can download the `poppler-data-0.4.7.tar.gz` file from https://poppler.freedesktop.org/ and extract the contents into `c:/dspdf/poppler`, so that the Directories `C:/dspdf/poppler/nameToUnicode` and so on exist.  You may need to install 7zip or similar, since Windows cannot by default read `.tar.gz`.

Result:

![it-works](https://cloud.githubusercontent.com/assets/782418/14233387/2f2b1042-f9c7-11e5-9e4b-d30adbe3a8a2.png)

**Comment by projekter** [comment]
Just a minute too late. That's what I just wanted to say.
I don't know whether there is a way to embed the encodings into the executable; I don't think so. But it should be no problem to change the poppler sources such that they will look for those encodings in the current application directory. I think this would be the most convenient way.
Btw., @zhangkmsjtu: I tried to compile the code you gave in your second comment with XeLaTeX and this pdf can be display without the need for the encodings. The only apparent difference I could find is that my XeLaTeX uses MicrosoftYaHei (TrueType) while yours does FandolHei-Regular (Type1).

**Comment by dannyedel** [comment]
> they will look for those encodings in the current application directory. I think this would be the most convenient way.

Agreed.  The only thing to watch out for is probably that the directory can have different names depending on the language and bits of the windows -- I've seen `c:/program files/dspdfviewer`, `c:/program files (x86)/dspdfviewer`, and `c:/programme/dspdfviewer` so far.  I don't know if these are really all mapped to the same thing (for example, when I open a german windows' drive on Linux, `c:/Benutzer` is really called `c:/users`) or if one has to actually figure out the path at runtime.

**Comment by zhangkmsjtu** [comment]
1. That's normal when the code is compiled with TeX Live 2015.
Texlive2015_Beamer_Chinese:
![texlive2015_beamer_chinese](https://cloud.githubusercontent.com/assets/12411065/14233586/935d3026-f9ff-11e5-8a2a-479f79c3098c.png)

2. It cannot be displayed correctly as the code is compiled with ShareLaTeX (https://www.sharelatex.com).
Sharelatex_Beamer_Chinese:
![sharelatex_beamer_chinese](https://cloud.githubusercontent.com/assets/12411065/14233588/a3446810-f9ff-11e5-98b6-d91e7f8500d1.png)

pdf files:
[pdf_TexLive2015_ShareLaTeX.zip](https://github.com/dannyedel/dspdfviewer/files/201446/pdf_TexLive2015_ShareLaTeX.zip)

**Comment by projekter** [comment]
Yes, of course. I am just updating poppler to the most recent version (if I have to edit its sources, this is a good moment) and will then post a new release.
And the folders are very different, not just aliases, so I'll need runtime-behavior. At the moment, poppler uses a constant for the path. I just changed this /usr/... constant to C:/dspdf in order to make it at least possible for Windows users to use the encodings.

**Comment by projekter** [comment]
Ha, this looks promising. The new poppler version has some flags in its cmake called "poppler_data_static". Perhaps that's what I looked for.

**Comment by projekter** [comment]
Please have a look at the [latest release](https://github.com/projekter/dspdfviewer/releases/tag/v1.14-141-g8aadd17), for me this fixes the problem.
As there was no way to do it statically, but poppler already provides means to search relative to the current application, I used the original poppler implementation of its most recent version and included a directory structure in the setup that conforms to that. As a result, dspdfviewer is now 11MB larger (but only 2MB for the setup).

**Comment by zhangkmsjtu** [comment]
GOOD JOB.
It's ok now.
