### ISSUE TITLE
mouse wheel advances 2 slides

### ISSUE THREAD

**Issue by nbecker** [dannyedel/dspdfviewer#182]
Just trying out 1st time
Built on fedora24/linux
using arrow keys advances 1 slide as expected, but mouse wheel moves by 2 slides
Using 2 screens, beamer, with
\usepackage{pgfpages}
\setbeameroption{show notes}
\setbeameroption{show notes on second screen=right}

**Comment by dannyedel** [comment]
Thanks for the bug report, I will look into it.

**Comment by dannyedel** [comment]
I can reproduce this in a Fedora24 "Workstation" virtual machine.  I'll look into it and try to figure out what's going on here.

**Comment by dannyedel** [comment]
I found a possible source of the bug.

@nbecker Can you try to compile the (possible) fix from #183, and check if that solves things on your real machine?  It seems to work on my VM.
