### ISSUE TITLE
Half-Screen Displayed

### ISSUE THREAD

**Issue by ghost** [dannyedel/dspdfviewer#195]
Can someone tel me how to use Dual-Screen PDF Viewer as my first trier displayed half-a page of my pdf horizontally.

**Comment by dannyedel** [comment]
I suggest you read [the manpage][1] to familiarize youself with the program and its options.  You are probably looking for the option `--full-page` if you have a PDF which is *not* built using the "show notes on second screen=right" latex-beamer feature.

[1]: http://dspdfviewer.danny-edel.de/manpage.html
