### ISSUE TITLE
Feature request: Key to toggle between notes and the actual slides.

### ISSUE THREAD

**Issue by zakkak** [dannyedel/dspdfviewer#20]
When presenting some slides might come without notes, in such cases I might want to focus on the slide itself (This is possible with a bit of latex hacking).  But more importantly sometimes while reading the notes I might want to focus to the slide for a second to refresh my memory about what my viewers see. 

't', for toggle, might be an appropriate key.

**Comment by dannyedel** [comment]
This does sound like a good idea. I'll implement it : )

I'll have to think about it a little bit how it will integrate with the caching mechanism (will second-screen-sized-mainpage purge second-screen-sized-notespage?) and prerendering.

**Comment by dannyedel** [comment]
I have written some code and started a pull-request.

Could you check out the branch and give feedback at the pullrequest if it does what you thought?

**Comment by zakkak** [comment]
Yes, it looks good.  Please pull it upstream.

Thanks :)

**Comment by dannyedel** [comment]
Done : ) Thanks for your feedback!
