### ISSUE TITLE
hyperlinks not clickable....

### ISSUE THREAD

**Issue by dio4ev** [dannyedel/dspdfviewer#200]
I it possible to use hyperlinks?
I found out that currently my hyperlinks in my latex beamer pdf are not clickable, although there is a flag `−l, −−hyperlink-support`.

Is this a bug or not implemented yet?
Is there a workaround so that I get support for clickable hyperlinks? If not then I cannot use this awesome program.

Thanks,
Jonas

**Comment by thomwiggers** [comment]
Sounds like a duplicate of #97

**Comment by dannyedel** [comment]
Yes, this is a missing feature, and yes, it is a duplicate of #97.

So I'm closing *this* ticket here, but the feature "should" get implemented "sometime soon".
