### ISSUE TITLE
Error with libboost > 1.66

### ISSUE THREAD

**Issue by ppoppitz** [dannyedel/dspdfviewer#202]
I have installed dspdfviewer from AUR.

After the latest update of boost(-libs) from 1.66 to 1.67 I get the error that libboost 1.66 cannot be found. After downgrading both boost and boost-libs everything works fine again.

PS:  not sure if I should report this in the AUR comments or here.

**Comment by clawoflight** [comment]
Did you rebuild dspdfviewer?
When using the AUR, you must manually rebuild packages whenever a dependency changes.

**Comment by ppoppitz** [comment]
Oops. Thank you for the reminder, now working again!
