### ISSUE TITLE
animatedgraphics package

### ISSUE THREAD

**Issue by ygalanak** [dannyedel/dspdfviewer#209]
Hi,

In one of my slides I use the animatedgraphics package (which combines several .eps pictures generating something like .gif). Though, when I open the .pdf with dspdfviewer, the animated slide doesn't play. Any ideas?

Best,
Y

**Comment by Rondom** [comment]
Just to clarify: Do you mean the [animate-package](https://www.ctan.org/pkg/animate)? Or is animatedgraphics some other package I don't know of? I searched a bit for animatedgraphics and could not find much,

**Comment by ygalanak** [comment]
Yes, that's the one I was talking about. I was thinking about the command I was calling on TeX while writing it - sorry.

**Comment by adimajo** [comment]
Same here. Control buttons are showing up correctly but are not clickable: it skips to the next slide. It's very frustrating since it seems to be working (other dual screen PDF presenters don't even behave correctly on these slides). Any workaround?

**Comment by Rondom** [comment]
Is there any FOSS PDF viewer that can handle those animations? Last I checked, Okular had at least some preliminary implementation for JS and animations, but it did not work with the animations created by this package.

**Comment by adimajo** [comment]
I'm on Mac, only thing I know is that it doesn't work on Preview but works on Adobe Acrobat Reader DC (the free one). No idea what it uses to render it though.

**Comment by dannyedel** [comment]
I have to close this ticket (and similar ones asking for animations / multimedia playback / etc) as "wontfix", since I don't have the resources to build and support this functionality myself.

Of course, if someone wants to implement this and send a pull request, please get in touch.
