### ISSUE TITLE
Certain PDF graphical elements do not appear in dspdfviewer

### ISSUE THREAD

**Issue by spectralflow** [dannyedel/dspdfviewer#212]
I attached two pictures and the original pdf, one screenshot of dspdfviewer and one screenshot of adobe. Dspdfviewer does not show certain graphical elements. In particular small round bullets 
[34_PDFsam_chp4.pdf](https://github.com/dannyedel/dspdfviewer/files/3950754/34_PDFsam_chp4.pdf)
do not show.
![Adobepic](https://user-images.githubusercontent.com/34473902/70627459-8ab9f880-1c26-11ea-925f-eb4dd83ce702.png)
![DSpic](https://user-images.githubusercontent.com/34473902/70627460-8ab9f880-1c26-11ea-86f5-c420d0e0a2ba.png)

**Comment by Rondom** [comment]
It displays fine for me on Debian sid.

Versions:

 * dspdfviewer version 1.15.1-1+b1
 * libpoppler-qt5 0.71.0-6
 * libqt5 5.12.5+dfsg-2

**Comment by projekter** [comment]
I can reproduce this problem on Windows, however, the very same issue is also present in Okular. Hence, it is not dspdfviewer related, but a problem of the underlying poppler library.
The dots in your document are not curves, but instead symbols in the Zapf Dingbats font. And this font is not embedded in the PDF file. When I tried embedding it using Acrobat (which somehow is able to render the file, although I don't have the font installed), it is unable to do so; when I try to convert every font to curves, it also fails for these dots (only the rest is converted properly) - a problem I never encountered before.
So I'd rather say that the greater surprise is that Acrobat and Foxit are able to display the page properly if the font is not installed. Try embedding it or just use curves (a simple `\tikz \fill[yourcolor] (0, 0) circle[radius=xx mm];` does the job at least equally well).

**Comment by spectralflow** [comment]
Good point, Thanks a lot for clearing up this issue.

I have also tried pympress yesterday. It shows these bullet points, but as little squares. There is something odd about these pictures. I have not produced them myself and will mention that to the creators of the pictures.

In any case, it's not a problem that dspdfviewer should worry about. So I will close this issue.
