### ISSUE TITLE
Build fails on Fedora 35 (warnings treated as errors)

### ISSUE THREAD

**Issue by nbecker** [dannyedel/dspdfviewer#218]
/home/nbecker/dspdfviewer/hyperlinkarea.cpp: In constructor ‘HyperlinkArea::HyperlinkArea(QLabel*, const AdjustedLink&)’:
/home/nbecker/dspdfviewer/hyperlinkarea.cpp:34:45: error: ‘const QPixmap* QLabel::pixmap() const’ is deprecated: Use the other overload which returns QPixmap by-value [-Werror=deprecated-declarations]
   34 |   const QPixmap* pixmap = imageLabel->pixmap();
      |                           ~~~~~~~~~~~~~~~~~~^~
In file included from /usr/include/qt5/QtWidgets/QLabel:1,
                 from /home/nbecker/dspdfviewer/hyperlinkarea.h:24,
                 from /home/nbecker/dspdfviewer/hyperlinkarea.cpp:21:
/usr/include/qt5/QtWidgets/qlabel.h:78:20: note: declared here
   78 |     const QPixmap *pixmap() const; // ### Qt 7: Remove function
      |                    ^~~~~~
cc1plus: all warnings being treated as errors

**Comment by dannyedel** [comment]
I am sorry for the very late response, but today I updated my debian system to bullseye, which includes Qt 5 version 5.15 LTS and can reproduce the issue (usage of deprecated function).

Expect updates soon, including updates to the CI pipeline to catch this.
