### ISSUE TITLE
Windows Binary: Runtime dependency MSVCP120.dll missing

### ISSUE THREAD

**Issue by dannyedel** [dannyedel/dspdfviewer#48]
@projekter, I tried to run your [binary] on a Windows 7 system, and it gives an error message about a missing `MSVCP120.dll`. I don't know where to get it from, but the `MSVC...` prefix makes me think its from Visual C++.

Please update [install instructions] on where to get it from, or include it in the zip (if you're allowed to do that).

![system-error](https://cloud.githubusercontent.com/assets/782418/8969441/0084bdd6-3633-11e5-946c-32e3d4fec0d8.png)

[binary]: https://github.com/projekter/dspdfviewer/releases/tag/v1.13-55-g3af1b8c
[install instructions]: https://github.com/dannyedel/dspdfviewer/blob/gh-pages/installation/windows.md

**Comment by projekter** [comment]
@dannyedel, I have updated the archive. Originally, I checked with Process Explorer which dependencies were loaded. These DLLs were not shown. I have now started the application in a plain VM and added the two missing DLLs. They are part of the Visual Studio Redistributable list, so inclusion is allowed.

**Comment by dannyedel** [comment]
Wonderful, thank you very much! Its also nice that you were allowed to include them.

As soon as I'm at the windows 7 machine again (probably around 17h CEST) I will try the package and post results (hopefully closing ticket).

**Comment by dannyedel** [comment]
I have tested again and I can confirm it works now. The only thing a bit confusing is that while the file-chooser is running, there's an additional blank console window named dspdfviewer.exe (which doesn't matter much, since as soon as I load a pdf I don't see it anyway, and it disappears when closing dspdfviewer.)

It just seems a bit odd, so if you know how to quickly turn it off, please send a pull request and enclose it in `#ifdef _WIN32`, such as

```cpp
#ifdef _WIN32
// do stuff to hide black window on windows
#endif
// shared-OS code
```

Anyway, it *works* and it almost runs as fast as on linux. So this issue's resolved :+1:

**Comment by raissel** [comment]
Hi, 
Can't run the binary in Windows 10 because of a bad allocation error. Anyone has it working on Windows 10? Any suggestion on how to get it working? 

Thanks!

![error](https://cloud.githubusercontent.com/assets/13871772/12637746/93bb55ce-c58f-11e5-9dfb-27cecf88e7b4.png)

**Comment by dannyedel** [comment]
@raissel thank you for reporting the problem.  But can I please ask you to report this as a [new issue][1]? It doesn't seem to mention the `MSCVP120.dll`, so I don't see why we should reopen this one.

[1]: https://github.com/dannyedel/dspdfviewer/issues/new

**Comment by raissel** [comment]
Done, thanks for your fast reply.

Please let me know if any solution comes out. I have an important
presentation by tomorrow and I can't manage to get the notes in one screen
and the presentation in the beamer.

best regards

On Thu, Jan 28, 2016 at 7:51 AM, Danny Edel <notifications@github.com>
wrote:

> @raissel <https://github.com/raissel> thank you for reporting the
> problem. But can I please ask you to report this as a new issue
> <https://github.com/dannyedel/dspdfviewer/issues/new>? It doesn't seem to
> mention the MSCVP120.dll, so I don't see why we should reopen this one.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dannyedel/dspdfviewer/issues/48#issuecomment-176040485>
> .
>



-- 
_________________________________________________________
Raissel Ramirez Orozco
Geometry and Graphics Group,
Universitat de Girona, Edifici P-IV
E-17071 Girona, SPAIN
