### ISSUE TITLE
Ask for inclusion in debian

### ISSUE THREAD

**Issue by dannyedel** [dannyedel/dspdfviewer#55]
Since the software is quite stable now, ask for inclusion in the official debian repository.

Update: ITP has been filed. See [debian bug 794319] for progress.

[debian bug 794319]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=794319

**Comment by dannyedel** [comment]
I am now working on a debian package.

**Comment by dannyedel** [comment]
Initial version available at http://danny-edel.de/deb/pool/main/d/dspdfviewer/dspdfviewer_1.13-1.dsc

However, this fails to build from source on **sid** right now, see #56 
 
It builds cleanly on **jessie**.

**Comment by dannyedel** [comment]
Revised version available at http://danny-edel.de/deb/pool/main/d/dspdfviewer/dspdfviewer_1.13-2.dsc

Currently verifying compiles

**Comment by dannyedel** [comment]
Works under sid amd64 and sid i386.

**Comment by dannyedel** [comment]
I have written an email to debian-mentors asking for a sponsor.

**Comment by dannyedel** [comment]
Improved version at http://danny-edel.de/deb/pool/main/d/dspdfviewer/dspdfviewer_1.13-1.dsc

**Comment by dannyedel** [comment]
The package is now being tracked at http://mentors.debian.net/package/dspdfviewer

**Comment by dannyedel** [comment]
Update! `dspdfviewer` was *included* in debian/sid.

Proof: https://tracker.debian.org/pkg/dspdfviewer

**Comment by LocutusOfBorg** [comment]
:)
