### ISSUE TITLE
Show presentation and notes at the same time

### ISSUE THREAD

**Issue by projekter** [dannyedel/dspdfviewer#58]
It can be very useful to see the same slide as the audience does on the own screen while the notes are also visible right to it (so the internal view shows the presentation as any normal reader would do). People with a small screen might not like this, but for those with a larger one with high resolution, it can be very useful.
I think 'd' for duplicate might be a good key to switch between the views.

**Comment by dannyedel** [comment]
You can already toggle between notes and presentation with `T`, I hope that helps in the meantime. Also beamer provides some™ way to integrate your main presentation view into the note side, but I can't provide a direct link right now.

I'll see that I integrate this when I refactor the rendering backend #60, generally trying to make more command-line parameters switchable during execution and improving performance of the rendering.

**Comment by projekter** [comment]
Fixed in https://github.com/dannyedel/dspdfviewer/pull/59.

**Comment by dannyedel** [comment]
fixed in 83eb2d899cc634323ac9b9b08cd75e9abf54ce1e by @projekter.
