### ISSUE TITLE
Manual Page on Windows: Possible to view or convert to native?

### ISSUE THREAD

**Issue by dannyedel** [dannyedel/dspdfviewer#61]
@projekter, after reading #58 I was wondering how users of the windows build would read the documentation *offline*, since I provide it in [manpage] format. I remember (this may be outdated) windows software normally had [chm] files as manuals that would be rendered by the OS.

Is there any way to
  * Display the manpage on windows? (or)
  * Convert it into a windows-compatible-format? (Not necessary chm, I just remember many programs used that)

[manpage]: https://github.com/dannyedel/dspdfviewer/blob/05bff2f8a7b006098200bf869fd892a94760c4e1/docs/dspdfviewer.1
[chm]: https://en.wikipedia.org/wiki/Microsoft_Compiled_HTML_Help

**Comment by projekter** [comment]
The manpage cannot be displayed, as there is no such thing as a "man" command which is universally used. Normally, command line programs print their help texts if they are called with a /?, /help, -help, -h, -?, --help or any parameter that sounds like that, depending on the developer's taste and background.
This would however not be possible, as I removed command line support from the release version.
Creating a help file would not be a problem. CHM is basically based on HTML; [this post](http://stackoverflow.com/questions/13433903/convert-all-linux-man-pages-to-text-html-or-markdown) says that manpages can automatically be convert to HTML. So if you can run the command `groff -mandoc -Thtml dspdfviewer.1`, this should produce a valid HTML output. I tried it with GNU for Windows, but this did not work. Can you execute this and provide the HTML files? I can then create a chm file.

**Comment by dannyedel** [comment]
You should be able to use [online manpage]  - it was created exactly this way (see [Makefile]). This already contains the section on i3, which was not included in v1.13.

So have also added an online version of the release manpage (currently v1.13) at http://dspdfviewer.danny-edel.de/manpage-release.html

[online manpage]: http://dspdfviewer.danny-edel.de/manpage.html
[Makefile]: https://github.com/dannyedel/dspdfviewer/blob/582cce7fa9e230708c6b70c3b5a54a5801dd157e/Makefile

**Comment by projekter** [comment]
I have just created the CHM file which is now included in the release archive. It is based on the release manpage (consistent to the version in the archive). i3 is not a Windows issue, so I think this section doesn't need to be integrated in the help file, as the command line switch will not work on Windows.

**Comment by dannyedel** [comment]
Sounds wonderful to me. Seems like the software is growing to be a proper cross-platform product, manual and everything :thumbsup: 

Is there anything left to do here? Otherwise, please close ticket.

**Comment by projekter** [comment]
I don't think something has to be done regarding the help file. But I am not the ticket owner, I can't close it.

**Comment by dannyedel** [comment]
Closed.
