### ISSUE TITLE
Timers not showing on Mac OSX

### ISSUE THREAD

**Issue by dannyedel** [dannyedel/dspdfviewer#74]
Bug found by @shaaati in #53, quote:
> [compiling current master] was stable, but none of the different timers was shown on the notes screen.

**Comment by dannyedel** [comment]
Note to people reading this ticket:

I don't own a mac myself, any help here is appreciated. My guesses are that it's either the timers getting rendered as black font on black background, or the font definitions is missing.

**Comment by dannyedel** [comment]
@shaaati, in the meantime #82 was developed, verified by wwwdata, and merged. Can you try to compile current master on your MacOS and test whether it solves the problem for you too?

**Comment by shaaati** [comment]
It works fine for me. Thanks for the nice work:).
