### ISSUE TITLE
Configurable bottom pane height

### ISSUE THREAD

**Issue by mmonaco** [dannyedel/dspdfviewer#8]
The previews of the previous and upcoming slides are nice, but almost too small to be useful. A config option to set the height, or maybe percentage of vertical space would be great.

It might also be worth considering whether the current slide needs to be listed in the prerender pane.

**Comment by zakkak** [comment]
I agree with the comment about the command line options, it will be more intuitive that way.

**Comment by dannyedel** [comment]
Just sorting this a little bit: I'm reducing this ticket to what the header says, making the preview-images' height variable.

I'm moving the other things to their own (smaller) tickets to easier track them.

**Comment by dannyedel** [comment]
This feature was added a month ago in pull request #39, closing this ticket.
